name: react-boilerplate-typescript-mobile build
on:
  push:
    branches:
      - feature/mobile
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@master
        env:
          ACCESS_TOKEN: ${{ secrets.githubtoken }}
          BRANCH: gh-pages
          FOLDER: build
          BUILD_SCRIPT: yarn install && npm run build
